In [1]:
import numpy as np

In [2]:
npz = np.load('processeddata.npz')
xtrain = npz['xtrain']
ytrain = npz['ytrain']
xtest = npz['xtest']
ytest = npz['ytest']

In [3]:
print(xtrain.shape, ytrain.shape, xtest.shape, ytest.shape)

(4681, 37) (4681,) (3122, 37) (3122,)


In [4]:
from sklearn.linear_model import LogisticRegression

In [5]:
reg = LogisticRegression(C=100, max_iter=200, class_weight='balanced')
reg.fit(xtrain, ytrain)

C:\Users\DELL\AppData\Local\conda\conda\envs\py3-TF2.0\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=100, class_weight='balanced', max_iter=200)

In [6]:
reg.score(xtrain, ytrain)

0.8102969450972014

In [7]:
from sklearn import metrics
from sklearn.metrics import mean_squared_error, precision_score, confusion_matrix, accuracy_score

def eval(ytest, ypred):
    print('\nEvaluation:')
    print('accuracy: '+ str(metrics.accuracy_score(ytest, ypred)))
    print('recall: ' + str(metrics.recall_score(ytest, ypred)))
    print('F1 score: ' + str(metrics.f1_score(ytest, ypred)))
    print('precision: ' + str(metrics.precision_score(ytest, ypred)))
    print('==================')
    print('\nConfusion Matrix:')
    print(' TN,  FP, FN, TP')
    print(confusion_matrix(ytest, ypred).ravel())
    print('==================')
    return

In [8]:
ypred = reg.predict(xtest)
eval(ytest, ypred)


Evaluation:
accuracy: 0.8142216527866752
recall: 0.855143031040779
F1 score: 0.8289085545722713
precision: 0.8042358328563252

Confusion Matrix:
 TN,  FP, FN, TP
[1137  342  238 1405]


In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
knn = KNeighborsClassifier(leaf_size=8, metric='manhattan',weights='uniform')
knn.fit(xtrain, ytrain)
ypredknn = knn.predict(xtest)
eval(ytest, ypredknn)


Evaluation:
accuracy: 0.8074951953875721
recall: 0.847839318320146
F1 score: 0.8225568349571891
precision: 0.7987385321100917

Confusion Matrix:
 TN,  FP, FN, TP
[1128  351  250 1393]


In [13]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
tree = DecisionTreeClassifier(criterion='entropy')
tree.fit(xtrain, ytrain)
ypredtree = tree.predict(xtest)
eval(ytest, ypredtree)


Evaluation:
accuracy: 0.9375400384368994
recall: 0.9427875836883749
F1 score: 0.9407834801093228
precision: 0.9387878787878788

Confusion Matrix:
 TN,  FP, FN, TP
[1378  101   94 1549]


In [18]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
forest = RandomForestClassifier(n_estimators=100, criterion='entropy')
forest.fit(xtrain, ytrain)
ypredforest = forest.predict(xtest)
eval(ytest, ypredforest)


Evaluation:
accuracy: 0.9612427930813581
recall: 0.9500912964090079
F1 score: 0.9626888683317915
precision: 0.975625

Confusion Matrix:
 TN,  FP, FN, TP
[1440   39   82 1561]


In [122]:
parameters = {
    'n_estimators': [5, 50, 100, 150, 200],
    'max_depth': list(range(1, 11)),
    'criterion':['gini','entropy'],
    'max_features': list(range(1,20)),
    'oob_score':[False,True],
}

In [123]:
grid = GridSearchCV(forest, parameters, cv=5, verbose=1, n_jobs=-1)
grid.fit(xtrain, ytrain)
ypredgrid = grid.predict(xtest)
evaluation(ytest, ypredgrid)

Fitting 5 folds for each of 3800 candidates, totalling 19000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    4.2s
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:   16.2s
[Parallel(n_jobs=-1)]: Done 434 tasks      | elapsed:   42.3s
[Parallel(n_jobs=-1)]: Done 784 tasks      | elapsed:  1.5min
[Parallel(n_jobs=-1)]: Done 1234 tasks      | elapsed:  2.4min
[Parallel(n_jobs=-1)]: Done 1784 tasks      | elapsed:  3.9min
[Parallel(n_jobs=-1)]: Done 2434 tasks      | elapsed:  5.8min
[Parallel(n_jobs=-1)]: Done 3184 tasks      | elapsed:  8.5min
[Parallel(n_jobs=-1)]: Done 4034 tasks      | elapsed: 12.1min
[Parallel(n_jobs=-1)]: Done 4984 tasks      | elapsed: 16.5min
[Parallel(n_jobs=-1)]: Done 6034 tasks      | elapsed: 21.9min
[Parallel(n_jobs=-1)]: Done 7184 tasks      | elapsed: 29.7min
[Parallel(n_jobs=-1)]: Done 8434 tasks      | elapsed: 39.9min
[Parallel(n_jobs=-1)]: Done 9784 tasks      | elapsed: 49.7min
[Parallel(n_jobs=-1)]: Done 11234 tasks      |

Evaluation Metrics:
Accuracy: 0.9580397181294042
Recall: 0.9404176904176904
F1 Score: 0.9589727528969622
Precision: 0.9782747603833866

Confusion Matrix:
 TN,  FP, FN, TP
[1460   34   97 1531]
